# -*- coding: utf-8 -*-
"""Mall_Customers_Clustering_Analysis_Data_Set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckzLUn_ZL6VryUk1wxn2hJToPODKZys1

# Import Libraries

**Import the usual libraries **
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()  # for plot styling
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (12, 6)

"""## Get the Data

** Use pandas to read driver-data.csv as a dataframe called df.**
"""

df=pd.read_csv('shopping_data.csv')
df.head()

# Check the no. of records -- It should be 4000
df.info()

# Check the Basic Distribution of Data
df.describe().T

"""Run the algorithm with K=2, which is the minimum number of clusters that can exist in a dataset."""

# Using the KMeans from sklearn
from sklearn.cluster import KMeans

"""** Create an instance of a k-means model with 2 clusters.**"""

kmeans = KMeans(n_clusters=5)
df_analyze = df.drop(['CustomerID', 'Genre'],axis=1)

"""**Fit the model to all the data, except for the id label.**"""

kmeans.fit(df_analyze)

"""** Q1. What are the cluster center vectors?**"""

kmeans.cluster_centers_

"""** Check the lables of data point
<br>Check the size of labels : should match dataset count 
   **
   <br>The cluster labels are returned in `kmeans.labels_`.
"""

print (kmeans.labels_)
print (len(kmeans.labels_))

"""** Q2. How many drivers are there in 1st and 2nd Cluster?**"""

print (type(kmeans.labels_))
unique, counts = np.unique(kmeans.labels_, return_counts=True)
print(dict(zip(unique, counts)))

"""** Plot the Cluster Data **"""

# plot the data 
df_analyze['cluster'] = kmeans.labels_
sns.set_style('whitegrid')
sns.lmplot('Annual Income (k$)','Spending Score (1-100)',data=df_analyze, hue='cluster',
           palette='coolwarm',size=6,aspect=1,fit_reg=False)

"""** What are the cluster center vectors?
<br> How many points are there in each of the Clusters?**
"""

kmeans_4 = KMeans(n_clusters=4)
kmeans_4.fit(df.drop(['CustomerID','Genre'],axis=1))
# kmeans_4.fit(df.drop('id',axis=1))
print(kmeans_4.cluster_centers_)	
unique, counts = np.unique(kmeans_4.labels_, return_counts=True)

kmeans_4.cluster_centers_
print(dict(zip(unique, counts)))

"""** Plot the Cluster Data **"""

# plot the data 
df_analyze['cluster'] = kmeans_4.labels_
sns.set_style('whitegrid')
sns.lmplot('Annual Income (k$)','Spending Score (1-100)',data=df_analyze, hue='cluster',
           palette='coolwarm',size=6,aspect=1,fit_reg=False)

